### ISSUE TITLE
zfs-dkms?

### ISSUE THREAD

**Issue by alaricljs** [n0xena/archzfs#9]
Would have swore I got 2.2.6 zfs-dkms from here...   Any plans on covering that (for 2.2.7)?

**Comment by n0xena** [comment]
I'll give it a look over the weekend

**Comment by n0xena** [comment]
testbuild looks good so far - will merge and upload after final test

**Comment by alaricljs** [comment]
Awesome, thanks so much.

**Comment by n0xena** [comment]
done
